### ISSUE TITLE
Won't Build 

### ISSUE THREAD

**Issue by minecraftchest1** [AdityaGupta1/minecraft-modding-book#26]
When i last tried running the command to run the build it would give an error saying not enough space when i had enough for what it needed. I have added more memory and reformatted sense then. I will try again soon to see if i can recreate the error. Also, when i tried running it on a different computer, it said unable do determine java version. I am not sure if either of the errors are related in any way or if anyone has had a similar problem but i wan't help. ASAP

**Comment by minecraftchest1** [comment]
Found the problem. I was "out of space". Really. Well, now that that's taken care of, I am getting the error listed above.
![image](https://user-images.githubusercontent.com/42992675/45200112-170b8d80-b224-11e8-9a19-d4c982e1aaa6.png)
Has anybody had this problem or a fix? I wan't to get modding ASAP. Please comment soon.

**Comment by AdityaGupta1** [comment]
try uninstalling JDK 10 and using JDK 8 instead
seems like this is a problem only with the latest versions of Java

**Comment by minecraftchest1** [comment]
Okay. I will ask my dad to do that. I just got my laptop taken so I can't try it right now.

**Comment by minecraftchest1** [comment]
Works with Java 8.
