### ISSUE TITLE
Don't see minecraft folder

### ISSUE THREAD

**Issue by minecraftchest1** [AdityaGupta1/minecraft-modding-book#27]
I don't see the Minecraft folder in Eclipse.
 
![image](https://user-images.githubusercontent.com/42992675/52825153-db011200-3078-11e9-8c4f-2e6f3786667a.png)

**Comment by AdityaGupta1** [comment]
Did you move the project folder after running the gradle commands? That is generally the cause of this error.

**Comment by minecraftchest1** [comment]
I don't think I did, but it was still giving me the problem after I ran gradle.

**Comment by minecraftchest1** [comment]
I am running in a folder called WorkSpace if that's any help.

**Comment by minecraftchest1** [comment]
It might help if I set up the workspace properly.
