### ISSUE TITLE
Chapter 6: New Commands

### ISSUE THREAD

**Issue by TheTechBrony** [AdityaGupta1/minecraft-modding-book#5]
In typing in the FlamingPigs code, I came across an error on lines 46 and 53, where it said:

The method sendErrorMessage(ICommandSender, String) in the type FlamingPigs is not applicable for the arguments (String).

I fixed it by replacing line 46 with this:

sendErrorMessage(sender, "Invalid number of arguments!");

and likewise with line 53.

There are a number of errors I found in the BlockFillerPositionSelector code. Please review it.

Other than that, this is good!

**Comment by AdityaGupta1** [comment]
I can't find any errors with the BlockFillerPositionSelector code. Maybe you imported the wrong type of List or Action? What were the exact imports that you used?

**Comment by AdityaGupta1** [comment]
Never mind, I figured out the problem. Currently, the instructions say to put the command code in BlockFillerPositionSelector instead of a new class, so I fixed the error.
