### ISSUE TITLE
Chapter 8: New Item & Chapter 9: Textures and Recipes

### ISSUE THREAD

**Issue by TheTechBrony** [AdityaGupta1/minecraft-modding-book#6]
When I follow the process you lay out for naming my new item exactly as shown, it doesn't work. This is also true for the new block.

In Example 8-7, there are is an error concerning illegal modifiers on onItemRightClick. What's that all about?

Couldn't find anything else wrong in here. Great work!

I couldn't find anything wrong with Chapter 9. All the recipes worked. However, the textures wouldn't load. This appears to be the last chapter that concerns modding. If you guys could send me an updated version of the book so I know how things are going, it would be great.

**Comment by AdityaGupta1** [comment]
What doesn't work in the item naming process? Does the name not show up, or can you not create the .lang file, or is the problem something else?

The onItemRightClick method didn't give me any errors about illegal modifiers.

As for the textures, did you follow the instructions exactly, or did you change some of the names or images? If you did, try doing it exactly as the instructions say.

**Comment by TheTechBrony** [comment]
"What doesn't work in the item naming process? Does the name not show up, or can you not create the .lang file, or is the problem something else?"
I input exactly the same text you say in the new file, which I called en_US.lang. I wrote in the new block line "tile.enderBlock.name=Block of Enderium". The name just won't show up.

"The onItemRightClick method didn't give me any errors about illegal modifiers."
Strange. I deleted the illegal modifiers, and other things started going wrong. Maybe the code in the book was mistyped?

"As for the textures, did you follow the instructions exactly, or did you change some of the names or images? If you did, try doing it exactly as the instructions say."
I did everything exactly as the instructions told me to.

**Comment by AdityaGupta1** [comment]
What name does the item have? Is it item.null.name?

The "onItemRightClick" method works fine for me. I don't know why it would not be working.

I fixed the textures error, the book says to make a "myMods" folder inside the already existing "myMods" folder.
