### ISSUE TITLE
Chapter 10: Sharing Mods

### ISSUE THREAD

**Issue by TheTechBrony** [AdityaGupta1/minecraft-modding-book#7]
This chapter really told me how easy it is to be a mod-maker.

I'd suggest you add the Mac command ./gradlew build to the text, or else someone could get confused.

You should tell the reader to use the installer with the exact same Forge version as their development version.

The Minecraft directory is inaccessible from the Finder in Mac, so you should tell them to go to the "Edit Profile" page in their Minecraft Launcher and click the button that says "Open Game Dir", then move the .jar file that contains their/other people's mods into the mods folder there.

This was a really good chapter for me. Just fix those simple content issues, and I think it's ready to read!

**Comment by AdityaGupta1** [comment]
I fixed all of these errors.
