### ISSUE TITLE
Appendices

### ISSUE THREAD

**Issue by TheTechBrony** [AdityaGupta1/minecraft-modding-book#8]
Appendix A was a pretty good introduction to Minecraft installation and gameplay.

Couldn't find anything wrong with Appendix B.

I'm glad you put in that biography of Devoxx4Kids in Appendix C. It's good for people to know about this.

May wanna fill in that index.

Thank you for letting me review this book! I can't wait for it to come out!

**Comment by AdityaGupta1** [comment]
What does "May wanna fill in that index." mean?

**Comment by arun-gupta** [comment]
Index will be populated by O'Reilly.
